version: '3.5'

networks:
  backend:
    name: "${NETWORK:-gestion}"

services:
  webserver:
    image: nginx:1.18.0-alpine
    container_name: hnweb_webserver
    restart: unless-stopped
    ports:
      - "${HOST_WEB_PORT:-7080}:80"
    volumes:
      - ./:/var/www/hnweb_api
      - .docker/nginx/default-vhost.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hnweb_app
    volumes:
      - .:/var/www/hnweb_api
      - .docker/php/conf.d/hnweb_api.ini:/usr/local/etc/php/conf.d/hnweb_api.ini
    environment:
      COMPOSER_HOME: /var/www/hnweb_api/.docker/.cache/composer
    working_dir: /var/www
    user: 1000:1000
    networks:
      - backend
